path_to_software: '/data/CGR_integration/hpv_igv/IGV-snapshot-automator-master/'
reference: '/data/CGR_integration/hpv_igv/ref/HPV_Ref_Alphas65_Pad400_hg19.fasta'
bam_directory: '/data/CGR_integration/hpv_igv/data/09272019_serial/bam/'
bed_direcotry: '/data/CGR_integration/hpv_igv/data/09272019_serial/igv_bed/'
# optional
  # output directory. default:output/ in workding directory 
output_directory: 'output/'
  # Height of the snapshot. default: 100
ht: '100' 
  # layout of snapshots in final pdf. default: 1x4
tile: '1x4'
  # memory for running IGV-snapshot-automator. default: 16g
mem: '16000'
